### ISSUE TITLE
Run client and server code on one port

### ISSUE THREAD

**Issue by thefrana** [andrasbacsai/svelte-fastify-starter#1]
Hi,
an interesting work you have done. Do you think it's possible to run both backend and frontend code on one port? Right now you have `:3001` for backend, but it is being proxied by Vite to `:3000`.

**Comment by andrasbacsai** [comment]
Hey, thanks! 🙂

Unfortunately, it's not possible IMO. You cannot run two different services on one port. The production build is running on one port, as Fastify serves the build frontend.
